#!/bin/sh
set -eu

if ! getent group abls >/dev/null 2>&1; then
  addgroup --system abls || true
fi

# Creation du repertoire /etc/abls
mkdir -p /etc/abls
chown root:abls /etc/abls
chmod 0770 /etc/abls

exit 0